#!/usr/bin/env node
/**
 * CSP generator & verifier — TAD §19.3, Dev Plan T-H2.
 *
 * Astro's built-in `security.csp` is incompatible with `<ClientRouter />`
 * (per-page meta hashes are lost after a client-side navigation), and this
 * site's View Transitions are mandated by TAD §6.5 — so the policy is
 * generated here instead (D-042):
 *
 *   1. Scan every page in dist/ for inline <script>/<style> content.
 *   2. Verify the CSP preconditions (no inline event handlers, no
 *      cross-origin scripts/styles/images, no embedded frames).
 *   3. Emit a strict policy — hash-allowlisted inline code, NO
 *      unsafe-inline (TAD §19.3 shape) — and sync it into the managed
 *      block in netlify.toml.
 *
 * Because the header ships the UNION of every page's hashes, content
 * swapped in by ClientRouter navigations is already allowlisted.
 *
 * netlify.toml is treated like a lockfile: run this after any build that
 * can change inline code, commit the result; CI re-runs with --check and
 * fails on drift (invariant I5 spirit).
 *
 * Usage:
 *   node scripts/generate-csp.mjs           # sync netlify.toml from dist/
 *   node scripts/generate-csp.mjs --check   # fail if netlify.toml drifts
 */
import { createHash } from 'node:crypto';
import { readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { join, relative } from 'node:path';
import process from 'node:process';

const DIST = new URL('../dist/', import.meta.url).pathname;
const NETLIFY_TOML = new URL('../netlify.toml', import.meta.url).pathname;
const BEGIN = '# BEGIN CSP — generated by scripts/generate-csp.mjs (do not edit by hand)';
const END = '# END CSP';

const failures = [];

function htmlFiles(dir) {
  const out = [];
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) out.push(...htmlFiles(full));
    else if (entry.name.endsWith('.html')) out.push(full);
  }
  return out;
}

function sha256(content) {
  return `'sha256-${createHash('sha256').update(content, 'utf8').digest('base64')}'`;
}

/** Extract inline (src-less) scripts and inline styles from one page. */
function extractInline(html) {
  const scripts = [...html.matchAll(/<script(?![^>]*\bsrc=)[^>]*>([\s\S]*?)<\/script>/g)]
    .map((m) => m[1])
    .filter((body) => body.trim() !== '');
  const styles = [...html.matchAll(/<style[^>]*>([\s\S]*?)<\/style>/g)].map((m) => m[1]);
  return { scripts, styles };
}

/** Preconditions that make a strict no-unsafe-inline policy viable. */
function verify(html, file) {
  const where = relative(DIST, file);
  if (/\son[a-z]+\s*=/i.test(html)) {
    failures.push(`${where}: inline event handler attribute found (forbidden under strict CSP)`);
  }
  for (const src of html.matchAll(/<script[^>]*\bsrc="([^"]+)"/g)) {
    if (!src[1].startsWith('/') && !src[1].startsWith('./')) {
      failures.push(`${where}: cross-origin script ${src[1]} — not allowed by script-src 'self'`);
    }
  }
  for (const href of html.matchAll(/<link[^>]*rel="stylesheet"[^>]*href="([^"]+)"/g)) {
    if (!href[1].startsWith('/') && !href[1].startsWith('./')) {
      failures.push(`${where}: cross-origin stylesheet ${href[1]} — not allowed by style-src 'self'`);
    }
  }
  for (const src of html.matchAll(/<img[^>]*\bsrc="([^"]+)"/g)) {
    if (!src[1].startsWith('/') && !src[1].startsWith('./') && !src[1].startsWith('data:')) {
      failures.push(`${where}: cross-origin image ${src[1]} — not allowed by img-src 'self' data:`);
    }
  }
  if (/<(iframe|object|embed)[\s>]/i.test(html)) {
    failures.push(`${where}: embedded frame/object found — object-src is 'none'`);
  }
}

function buildPolicy(scriptHashes, styleHashes) {
  return [
    "default-src 'self'",
    `script-src 'self' ${[...scriptHashes].sort().join(' ')}`,
    `style-src 'self' ${[...styleHashes].sort().join(' ')}`,
    "img-src 'self' data:",
    "font-src 'self'",
    "connect-src 'self'",
    "form-action 'self'",
    "base-uri 'self'",
    "object-src 'none'",
    "frame-ancestors 'none'",
    'upgrade-insecure-requests',
  ].join('; ');
}

function block(policy) {
  return [
    BEGIN,
    '# Strict CSP per TAD §19.3: hash-allowlisted inline scripts/styles, no',
    '# unsafe-inline. The union of every page\'s hashes covers content swapped',
    '# in by ClientRouter navigations (D-042). frame-ancestors blocks',
    '# clickjacking; it can only be delivered via header, not <meta>.',
    '[[headers]]',
    '  for = "/*"',
    '  [headers.values]',
    `    Content-Security-Policy = "${policy}"`,
    END,
  ].join('\n');
}

// ── Main ────────────────────────────────────────────────────────────────────
const files = htmlFiles(DIST);
if (files.length === 0) {
  console.error('generate-csp: dist/ not found or empty — run `npm run build` first.');
  process.exit(1);
}

const scriptHashes = new Set();
const styleHashes = new Set();
for (const file of files) {
  const html = readFileSync(file, 'utf8');
  verify(html, file);
  const { scripts, styles } = extractInline(html);
  for (const body of scripts) scriptHashes.add(sha256(body));
  for (const body of styles) styleHashes.add(sha256(body));
}

if (failures.length > 0) {
  console.error('generate-csp: CSP preconditions FAILED:');
  for (const failure of failures) console.error(`  ✗ ${failure}`);
  process.exit(1);
}

const policy = buildPolicy(scriptHashes, styleHashes);
const generated = block(policy);
const toml = readFileSync(NETLIFY_TOML, 'utf8');

if (!toml.includes(BEGIN) || !toml.includes(END)) {
  console.error('generate-csp: managed CSP block missing from netlify.toml.');
  process.exit(1);
}

const current = toml.slice(toml.indexOf(BEGIN), toml.indexOf(END) + END.length);

if (process.argv.includes('--check')) {
  if (current === generated) {
    console.log(
      `generate-csp: OK — netlify.toml in sync (${scriptHashes.size} script hashes, ${styleHashes.size} style hashes across ${files.length} pages).`,
    );
  } else {
    console.error('generate-csp: DRIFT — netlify.toml CSP block does not match the build.');
    console.error('Run `node scripts/generate-csp.mjs` and commit the updated netlify.toml.');
    process.exit(1);
  }
} else {
  writeFileSync(NETLIFY_TOML, toml.replace(current, generated));
  console.log(
    `generate-csp: netlify.toml updated (${scriptHashes.size} script hashes, ${styleHashes.size} style hashes across ${files.length} pages).`,
  );
}
